// =============================================================================
// News Trend Analyzer — レポート出力
// =============================================================================
// 傾向分析結果を Markdown / コンソール形式で出力する。
// =============================================================================

import {
  type TrendReport,
  type IndustryBreakdown,
  ANALYSIS_WINDOW_LABELS,
} from './types.js';

// ---------------------------------------------------------------------------
// Markdown レポート生成
// ---------------------------------------------------------------------------

function sentimentBar(dist: Record<string, number>): string {
  const total = Object.values(dist).reduce((s, v) => s + v, 0);
  if (total === 0) return '（データなし）';
  const pct = (key: string) => Math.round(((dist[key] || 0) / total) * 100);
  return `🟢 ${pct('positive')}% / 🔴 ${pct('negative')}% / ⚪ ${pct('neutral')}% / 🟡 ${pct('mixed')}%`;
}

function changeRateLabel(rate: number | null): string {
  if (rate === null) return '—';
  if (rate > 0) return `↑ +${rate}%`;
  if (rate < 0) return `↓ ${rate}%`;
  return '→ 0%';
}

function industrySection(ind: IndustryBreakdown): string {
  const lines: string[] = [
    `### ${ind.industry_name}`,
    '',
    `| 指標 | 値 |`,
    `|------|-----|`,
    `| 記事数 | ${ind.article_count} |`,
    `| 前期比 | ${changeRateLabel(ind.change_rate)} |`,
    `| 高インパクト | ${ind.high_impact_count}件 |`,
    `| センチメント | ${sentimentBar(ind.sentiment_distribution)} |`,
    '',
  ];

  if (ind.top_themes.length > 0) {
    lines.push('**トップテーマ:**');
    for (const theme of ind.top_themes) {
      lines.push(`- ${theme.theme_label}（${theme.count}件）`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function toMarkdown(report: TrendReport): string {
  const windowLabel = ANALYSIS_WINDOW_LABELS[report.window];
  const lines: string[] = [];

  // ヘッダー
  lines.push(`# ニュース傾向分析レポート — ${windowLabel}`);
  lines.push('');
  lines.push(`**レポートID:** ${report.id}`);
  lines.push(`**対象期間:** ${report.period.from} 〜 ${report.period.to}`);
  lines.push(`**生成日時:** ${report.generated_at}`);
  lines.push(`**対象記事数:** ${report.total_articles}件（前期: ${report.previous_period_articles}件）`);
  lines.push('');

  // エグゼクティブサマリー
  if (report.executive_summary) {
    lines.push('## エグゼクティブサマリー');
    lines.push('');
    lines.push(report.executive_summary);
    lines.push('');
  }

  // 全体センチメント
  lines.push('## 全体センチメント');
  lines.push('');
  lines.push(sentimentBar(report.overall_sentiment));
  lines.push('');

  // 業界別ブレイクダウン
  lines.push('## 業界別分析');
  lines.push('');
  for (const ind of report.industry_breakdown) {
    lines.push(industrySection(ind));
  }

  // テーマランキング
  if (report.theme_ranking.length > 0) {
    lines.push('## テーマランキング（全業界横断）');
    lines.push('');
    lines.push('| 順位 | テーマ | 記事数 |');
    lines.push('|------|--------|--------|');
    for (let i = 0; i < Math.min(report.theme_ranking.length, 10); i++) {
      const t = report.theme_ranking[i];
      lines.push(`| ${i + 1} | ${t.theme_label} | ${t.count} |`);
    }
    lines.push('');
  }

  // 新興トレンド
  if (report.emerging_trends.length > 0) {
    lines.push('## 新興トレンド（急上昇テーマ）');
    lines.push('');
    for (const trend of report.emerging_trends) {
      lines.push(
        `- **${trend.theme_label}**: ${trend.previous_count} → ${trend.current_count}件（+${trend.growth_rate}%）` +
          ` — ${trend.related_industries.join(', ')}`,
      );
    }
    lines.push('');
  }

  // クロスインダストリー相関
  if (report.cross_industry_correlations.length > 0) {
    lines.push('## クロスインダストリー相関');
    lines.push('');
    lines.push('| 業界ペア | 共通記事数 | 相関スコア | 共通テーマ |');
    lines.push('|----------|-----------|-----------|-----------|');
    for (const corr of report.cross_industry_correlations.slice(0, 10)) {
      lines.push(
        `| ${corr.industries.join(' × ')} | ${corr.overlap_count} | ${corr.correlation_score} | ${corr.shared_themes.slice(0, 3).join(', ')} |`,
      );
    }
    lines.push('');
  }

  // ビジネスインサイト候補
  if (report.insight_candidates.length > 0) {
    lines.push('## ビジネスインサイト候補');
    lines.push('');
    for (const insight of report.insight_candidates) {
      const typeLabel: Record<string, string> = {
        cross_industry: '🔗 業界横断',
        emerging_trend: '📈 新興トレンド',
        sentiment_shift: '⚠️ センチメント変化',
        convergence: '🌐 メガトレンド収束',
      };
      lines.push(
        `### ${typeLabel[insight.type] || insight.type}（確信度: ${Math.round(insight.confidence * 100)}%）`,
      );
      lines.push('');
      lines.push(insight.description);
      lines.push('');
      lines.push(`> 根拠記事: ${insight.evidence_articles.join(', ')}`);
      lines.push('');
    }
  }

  // フッター
  lines.push('---');
  lines.push(`*Generated by HARMONIC insight News Trend Analyzer v1.0*`);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// コンソール出力（簡易版）
// ---------------------------------------------------------------------------

export function toConsole(report: TrendReport): string {
  const windowLabel = ANALYSIS_WINDOW_LABELS[report.window];
  const lines: string[] = [];

  lines.push(`\n===== ニュース傾向分析: ${windowLabel} (${report.period.from} 〜 ${report.period.to}) =====\n`);
  lines.push(`記事数: ${report.total_articles}件（前期: ${report.previous_period_articles}件）\n`);

  lines.push('--- 業界別 ---');
  for (const ind of report.industry_breakdown) {
    lines.push(
      `  ${ind.industry_name}: ${ind.article_count}件 ${changeRateLabel(ind.change_rate)} | 高インパクト: ${ind.high_impact_count}`,
    );
  }

  if (report.emerging_trends.length > 0) {
    lines.push('\n--- 新興トレンド ---');
    for (const trend of report.emerging_trends) {
      lines.push(`  ${trend.theme_label}: +${trend.growth_rate}% (${trend.current_count}件)`);
    }
  }

  if (report.insight_candidates.length > 0) {
    lines.push('\n--- ビジネスインサイト候補 ---');
    for (const insight of report.insight_candidates.slice(0, 5)) {
      lines.push(`  [${insight.type}] ${insight.description}`);
    }
  }

  return lines.join('\n');
}
